#!/usr/bin/env python3
"""D14 closure trade study — roll-top vs clamped bar vs gasketed rigid.

The question is whether the Rev C roll-top is the right closure at 10 m, or
whether a clamped bar or a rigid gasketed lid earns its keep. The deciding
calculation is beam bow: a clamped bar only seals if it does not bow away from
the gasket line between its latches, and that requirement sizes the bar.

Run: python blueprints/rolltop/closure_trade.py
Writes: closure-trade-study.md
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from rev_c_dimensions import (
    FABRIC_AREAL,
    RATED_DEPTH_M,
    ROLL_CONTACT_W,
    SEAL_PRESSURE_FACTOR,
    SIDE_LAP_WELD,
    derive,
    head_pressure_mpa,
)

HERE = Path(__file__).resolve().parent

# --- inputs -------------------------------------------------------------

SEAL_FACE_W = 6.0  # elastomer contact strip width on a clamped bar, mm
GASKET_SECTION = 1.5  # silicone bead diameter, mm
GASKET_SQUEEZE = 0.30  # fraction compressed at full clamp
BOW_BUDGET = 0.25  # allowable mid-span bow as a fraction of the squeeze

LATCH_EAR = 5.5  # bar overhang beyond the mouth to each latch centre, mm
BAR_FACE_Z = 8.0  # bar dimension along the pouch height, mm

# Fold-over the mouth needs for a bar closure: one fold plus a welded hem,
# against the 78 mm the three-fold roll eats.
BAR_MOUTH_FOLD = 25.0

MATERIALS = {
    "PPA GF30": dict(E=11000.0, rho=1.55),
    "PA66 GF50": dict(E=16000.0, rho=1.72),
    "6061-T6 aluminium": dict(E=68900.0, rho=2.70),
}


@dataclass
class BarResult:
    material: str
    span: float
    latches: int
    thickness: float
    inertia_req: float
    mass_g: float
    stress: float


def line_load(pressure_mpa: float, face_w: float) -> float:
    """Sealing load per mm of seal line, N/mm."""
    return SEAL_PRESSURE_FACTOR * pressure_mpa * face_w


def required_inertia(w: float, span: float, bow: float, E: float) -> float:
    """Second moment needed so a simply supported bar bows less than `bow`.

    delta = 5 w L^4 / (384 E I)
    """
    return 5.0 * w * span**4 / (384.0 * E * bow)


def bar_thickness(inertia: float, face_z: float) -> float:
    """Rectangular section, bending in the clamp direction: I = face_z * h^3 / 12."""
    return (12.0 * inertia / face_z) ** (1.0 / 3.0)


def bar_stress(w: float, span: float, face_z: float, h: float) -> float:
    """Peak bending stress, simply supported, uniform load."""
    moment = w * span**2 / 8.0
    section_modulus = face_z * h * h / 6.0
    return moment / section_modulus


def size_bar(material: str, mouth_w: float, latches: int, w: float, bow: float) -> BarResult:
    props = MATERIALS[material]
    overall = mouth_w + 2 * LATCH_EAR
    span = overall / (latches - 1)
    inertia = required_inertia(w, span, bow, props["E"])
    h = bar_thickness(inertia, BAR_FACE_Z)
    volume = overall * BAR_FACE_Z * h
    return BarResult(
        material=material,
        span=span,
        latches=latches,
        thickness=h,
        inertia_req=inertia,
        mass_g=volume / 1000.0 * props["rho"],
        stress=bar_stress(w, span, BAR_FACE_Z, h),
    )


def main() -> None:
    d = derive()
    p = head_pressure_mpa(RATED_DEPTH_M)
    mouth = d["body_flat_w"]
    bow = GASKET_SECTION * GASKET_SQUEEZE * BOW_BUDGET
    w = line_load(p, SEAL_FACE_W)
    total_bar_load = w * mouth

    bars = [
        size_bar(m, mouth, n, w, bow)
        for n in (2, 3)
        for m in ("PPA GF30", "PA66 GF50", "6061-T6 aluminium")
    ]

    # Mass and panel deltas for swapping the roll out for a bar.
    roll_hw = 11.0 + 4.0 + 1.7  # buckles + webbing + mouth batten, from the Rev C budget
    panel_saved = d["roll_consumed"] - BAR_MOUTH_FOLD
    fabric_saved = 2 * panel_saved * (mouth + 2 * SIDE_LAP_WELD) / 1e6 * FABRIC_AREAL

    out: list[str] = []
    out.append("# D14 closure trade study — is the roll-top right at 10 m?")
    out.append("")
    out.append(
        f"Generated by `closure_trade.py`. Rated depth {RATED_DEPTH_M:.0f} m, "
        f"internal pressure {p * 1000:.0f} kPa, mouth width {mouth:.0f} mm."
    )
    out.append("")
    out.append(
        "> **Acted on.** The recommendation below is built as Rev D, drawing `D14-RT-004`. Rev D moved "
        "the latches inboard of the mouth ends rather than onto them, which cut the span and took the "
        "bar from the 8.0 mm assumed here down to 6.0 mm."
    )
    out.append("")
    out.append("## Seal load: the bar asks for less")
    out.append("")
    out.append(
        f"Both closures have to hold {SEAL_PRESSURE_FACTOR:.0f}x internal pressure across their contact "
        f"strip, so the load follows the strip width. A {SEAL_FACE_W:.0f} mm bar face needs "
        f"{w:.2f} N/mm, or {total_bar_load:.0f} N across the mouth, against the "
        f"{d['clamp_force_total']:.0f} N the roll needs over its wider {ROLL_CONTACT_W:.0f} mm "
        f"bundle — {(1 - total_bar_load / d['clamp_force_total']) * 100:.0f}% less clamp for the user to "
        "generate. A narrow, well-defined seal line is cheaper to load than a wide, vague one."
    )
    out.append("")
    out.append("## What sizes a clamped bar")
    out.append("")
    out.append(
        f"A bar seals only if it stays flat against the gasket between its latches. With a "
        f"{GASKET_SECTION:.1f} mm bead compressed {GASKET_SQUEEZE:.0%}, the squeeze is "
        f"{GASKET_SECTION * GASKET_SQUEEZE:.2f} mm, and spending more than {BOW_BUDGET:.0%} of that "
        f"on mid-span bow means the centre of the mouth is sealing on less than the ends. "
        f"That caps bow at {bow:.3f} mm and is the binding constraint."
    )
    out.append("")
    out.append("| Material | Latches | Span | Bar thickness | Mass | Bending stress |")
    out.append("| --- | --- | --- | --- | --- | --- |")
    for b in bars:
        out.append(
            f"| {b.material} | {b.latches} | {b.span:.0f} mm | {b.thickness:.1f} mm | "
            f"{b.mass_g:.1f} g | {b.stress:.1f} MPa |"
        )
    out.append("")
    two_ppa = next(b for b in bars if b.latches == 2 and b.material == "PPA GF30")
    three_ppa = next(b for b in bars if b.latches == 3 and b.material == "PPA GF30")
    two_al = next(b for b in bars if b.latches == 2 and b.material == "6061-T6 aluminium")
    two_masses = [b.mass_g for b in bars if b.latches == 2]
    out.append(
        f"Deflection governs everywhere — peak stress never exceeds {max(b.stress for b in bars):.0f} MPa "
        "against flexural strengths in the hundreds, so these bars are stiffness-limited, not "
        "strength-limited. Three consequences:"
    )
    out.append("")
    out.append(
        f"- **Material barely matters.** Every two-latch bar lands between {min(two_masses):.0f} and "
        f"{max(two_masses):.0f} g whatever it is made of, because stiffness goes as thickness cubed "
        "while mass goes as thickness times density, and the two effects very nearly cancel across "
        "this material set. Choosing aluminium buys a thinner bar, not a lighter one."
    )
    out.append(
        f"- **Two latches does not work in plastic.** A PPA bar latched only at its ends needs to be "
        f"{two_ppa.thickness:.0f} mm thick, which is thicker than the whole {d['sealed_t']:.1f} mm pouch. "
        f"Span enters as the fourth power, so this is not a small miss."
    )
    out.append(
        f"- **Either add a third latch or go metal.** A centre latch halves the span and drops the PPA "
        f"bar to {three_ppa.thickness:.1f} mm and {three_ppa.mass_g:.0f} g. Keeping two latches and "
        f"switching to aluminium gives {two_al.thickness:.1f} mm and {two_al.mass_g:.0f} g."
    )
    out.append("")
    out.append("## Mass and material, bar against roll")
    out.append("")
    out.append("| Item | Roll-top | Clamped bar, 3 latches |")
    out.append("| --- | --- | --- |")
    out.append(f"| Closure hardware | {roll_hw:.1f} g | {three_ppa.mass_g:.1f} g + 3 latches |")
    out.append(f"| Mouth material consumed | {d['roll_consumed']:.0f} mm | {BAR_MOUTH_FOLD:.0f} mm |")
    out.append(f"| Fabric saved | — | {fabric_saved:.1f} g |")
    out.append(f"| Net mass change | — | {three_ppa.mass_g - roll_hw - fabric_saved:+.1f} g before latches |")
    out.append("")
    out.append("## The reason to switch is not mass")
    out.append("")
    out.append(
        "Mass is a wash. The case for the bar is that it changes the character of the leak path and "
        "the honesty of the sensing:"
    )
    out.append("")
    out.append(
        "- **Leak path.** A roll seals along a spiral, and the ends of that spiral are where dry bags "
        "actually leak: the folded edges form a small channel that no amount of strap tension closes. "
        "A bar seals along a straight line against a defined gasket, which is a geometry you can "
        "inspect, measure and calculate."
    )
    out.append(
        "- **Creep.** Roll contact pressure is carried by TPU-faced fabric in sustained compression, "
        f"which relaxes. A {RATED_DEPTH_M:.0f} m rating held for 30 minutes is exactly the duration "
        "over which that relaxation matters, and it is not something the load cells can correct for "
        "once the user has walked away from the buckle."
    )
    out.append(
        "- **Sensing fidelity.** This is the strongest argument. On the roll, the cells read strap "
        f"tension through a compressible {d['roll_dia']:.0f} mm bundle, so they infer interface pressure "
        "through the most compliant element in the stack. On a bar, the cells sit directly in the load "
        "path under the gasket line. The clamp-verification feature the whole product is named for only "
        "measures what it claims to measure in the bar version."
    )
    out.append("")
    out.append("## What the bar costs")
    out.append("")
    out.append(
        "- A second rigid part, roughly mouth-width, that does not collapse. The `designs.js` warning "
        "that the hard bezel edge is an impact weak point now applies to the bar as well."
    )
    out.append(
        "- Grit tolerance goes down, not up. A roll closes over sand; a gasket does not. For a beach "
        "and boat-deck product that is a real regression and argues for a wipeable, exposed gasket "
        "land rather than a recessed groove."
    )
    out.append("- Three latches is three user actions instead of two, and a centre latch is easy to forget.")
    out.append("")
    out.append("## Recommendation")
    out.append("")
    out.append(
        f"Move to a clamped bar with a centre latch, {three_ppa.thickness:.1f} mm in PPA GF30, and keep "
        "the four load cells but relocate them into the bar and its land. It is mass-neutral, it turns "
        "a spiral friction seal into a straight gasket line, and it makes the sensing measure the seal "
        f"instead of a proxy for it. If the third latch tests badly with cold hands, the fallback is "
        f"two latches with the {two_al.thickness:.1f} mm aluminium bar at {two_al.mass_g:.0f} g."
    )
    out.append("")
    out.append(
        "The rigid gasketed lid is not carried forward. At this mouth width it is a rigid case top, "
        "which ends the soft-body premise that puts D14 in the non-rigid family at all. If the "
        f"programme wants a genuine {RATED_DEPTH_M:.0f} m gasketed closure, the honest move is to build "
        "an A-family rigid case, not to armour a pouch until it becomes one."
    )
    out.append("")
    out.append("## Still unproven")
    out.append("")
    out.append(
        f"- The {bow:.3f} mm bow budget is an assumption about how unevenly a gasket can be loaded "
        "before it leaks. It needs a bench test on a bar with a deliberately sloppy centre latch."
    )
    out.append(
        "- Nothing here changes the fact that the bezel-to-body weld and the glass bond are still "
        "the two longest unvalidated seal paths on the product. The closure is not the only risk, "
        "and fixing it does not make the pouch waterproof on its own."
    )
    out.append("")

    (HERE / "closure-trade-study.md").write_text("\n".join(out), encoding="utf-8")

    print(f"mouth {mouth:.0f} mm, seal line load {w:.2f} N/mm, {total_bar_load:.0f} N total")
    print(f"bow budget {bow:.3f} mm")
    for b in bars:
        print(
            f"  {b.material:<20} {b.latches} latches  span {b.span:5.1f}  "
            f"h {b.thickness:5.1f} mm  {b.mass_g:5.1f} g  {b.stress:5.1f} MPa"
        )
    print(f"fabric saved by dropping the roll: {fabric_saved:.1f} g")
    print("wrote closure-trade-study.md")


if __name__ == "__main__":
    main()
