/** Nereid Interface Catalog — build blueprints data (Rev A) */
window.NEREID_DESIGNS = [
  {
    id: "A1",
    name: "Lightline Mg",
    family: "A",
    familyTitle: "Force-Sensed Rigid",
    depthM: 6,
    weightG: 153,
    sensing: "Load cell",
    image: "assets/A1-lightline-mg-blueprint.png",
    cadParts: {"shell_front": {"stl": "shell_front.stl", "step": "shell_front.step", "volume_mm3": 56335.3}, "shell_back": {"stl": "shell_back.stl", "step": "shell_back.step", "volume_mm3": 65534.1}, "window_blank": {"stl": "window_blank.stl", "step": "window_blank.step", "volume_mm3": 15540.0}},
    envelope: "rigid-standard",
    outer: { L: 168, W: 88, H: 26 },
    aperture: { L: 148, W: 70 },
    window: { material: "Alumino-silicate glass", t: 1.5, mount: "silicone diaphragm" },
    shell: { material: "AZ91D Mg thixomolded + PEO", t: 1.8 },
    bom: [
      { qty: 1, part: "Mg frame AZ91D thixomold", note: "PEO coat all surfaces" },
      { qty: 1, part: "Glass window 148×70×1.5 mm", note: "Chemically strengthened" },
      { qty: 1, part: "Silicone diaphragm gasket", note: "Shore A 40, bonded" },
      { qty: 4, part: "TE FX29 load cell", note: "Corner mounts" },
      { qty: 1, part: "24-bit ADC + MCU PCB", note: "Moment-balance firmware" },
      { qty: 1, part: "LiPo + BLE module", note: "~16 g budget" },
      { qty: 2, part: "Side latches + O-ring seals", note: "1.5 mm section" },
      { qty: 1, part: "Purge / equalize valve", note: "Dry-air pocket" },
    ],
    assembly: [
      "PEO-coat Mg frame; mask O-ring grooves before coat if needed.",
      "Bond load cells into corner pockets with structural epoxy; torque limit per TE datasheet.",
      "Bond glass to silicone diaphragm; cure 24 h.",
      "Seat diaphragm/window stack into frame; verify free float on cells.",
      "Install PCB, battery, BLE; route flex clear of diaphragm travel.",
      "Fit O-rings, latches, valve. Pressure-check dry to 1.5× rating.",
      "Calibrate zero under known hydrostatic fixture; store offsets.",
    ],
    tools: ["Thixomold tooling or CNC Mg billet alt", "PEO bath", "24-bit ADC bench", "Pressure pot 2 bar"],
    notes: "Primary risk: PEO breach at machined edges. Mask and re-coat after any rework.",
  },
  {
    id: "A2",
    name: "Carbonshell",
    family: "A",
    familyTitle: "Force-Sensed Rigid",
    depthM: 6,
    weightG: 147,
    sensing: "Load cell",
    image: "assets/A2-carbonshell-blueprint.png",
    cadParts: {"shell_front": {"stl": "shell_front.stl", "step": "shell_front.step", "volume_mm3": 53213.3}, "shell_back": {"stl": "shell_back.stl", "step": "shell_back.step", "volume_mm3": 57240.2}, "window_blank": {"stl": "window_blank.stl", "step": "window_blank.step", "volume_mm3": 15540.0}},
    envelope: "rigid-standard",
    outer: { L: 168, W: 88, H: 25 },
    aperture: { L: 148, W: 70 },
    window: { material: "Alumino-silicate glass", t: 1.5, mount: "silicone diaphragm" },
    shell: { material: "CFRP QI [0/45/90/−45]", t: 1.2 },
    bom: [
      { qty: 1, part: "CFRP monocoque shell", note: "Co-cure GF bosses for cells" },
      { qty: 1, part: "Glass-filled nylon bezel", note: "Latch bearing faces" },
      { qty: 1, part: "PPS RF window insert", note: "Tune to phone antenna map" },
      { qty: 1, part: "Glass + diaphragm", note: "Same as A1" },
      { qty: 4, part: "TE FX29 load cell", note: "On GF inserts only" },
      { qty: "set", part: "Ti fasteners", note: "No Al against carbon" },
      { qty: 1, part: "PCB + battery + BLE", note: "" },
    ],
    assembly: [
      "Lay up QI CFRP; co-cure glass-fiber fastener bosses.",
      "Bond nylon bezel; machine RF slot; backfill PPS.",
      "Mount load cells on GF bosses only — never into carbon plies.",
      "Install window/diaphragm stack; Ti fasteners throughout.",
      "Validate BLE RSSI with phone installed; enlarge RF window if needed.",
      "Salt-fog verify with Ti-only hardware.",
    ],
    tools: ["Composite autoclave/oven", "RF window fixture", "Ti hardware kit"],
    notes: "RF window is phone-specific. Prototype with copper-tape tuning before PPS pour.",
  },
  {
    id: "A3",
    name: "Skeleton",
    family: "A",
    familyTitle: "Force-Sensed Rigid",
    depthM: 10,
    weightG: 168,
    sensing: "Load cell",
    image: "assets/A3-skeleton-blueprint.png",
    cadParts: {"rib_cage": {"stl": "rib_cage.stl", "step": "rib_cage.step", "volume_mm3": 90547.0}, "window_cartridge": {"stl": "window_cartridge.stl", "step": "window_cartridge.step", "volume_mm3": 17135.5}, "shell_back": {"stl": "shell_back.stl", "step": "shell_back.step", "volume_mm3": 38962.6}, "window_blank": {"stl": "window_blank.stl", "step": "window_blank.step", "volume_mm3": 15540.0}},
    envelope: "rigid-standard",
    outer: { L: 170, W: 90, H: 28 },
    aperture: { L: 148, W: 70 },
    window: { material: "Glass cartridge", t: 1.5, mount: "captive double O-ring cartridge" },
    shell: { material: "7075-T6 ribs + PPA overmold", t: "lattice" },
    bom: [
      { qty: 1, part: "7075-T6 rib cage CNC", note: "Open lattice" },
      { qty: 1, part: "PPA overmold", note: "Grip + edge protection" },
      { qty: 1, part: "Window cartridge assembly", note: "Glass + diaphragm + 4 cells + O-rings" },
      { qty: 2, part: "Captive M3 screws", note: "Coin-slot heads" },
      { qty: 1, part: "Mesh sand pre-filter", note: "For open lattice" },
      { qty: 1, part: "PCB + battery + BLE", note: "" },
    ],
    assembly: [
      "CNC rib cage; overmold PPA.",
      "Build cartridge offline: cells → carrier → diaphragm → glass → double O-ring.",
      "Drop cartridge into cage; tighten two captive screws coin-tight.",
      "Inspect both seal planes (cartridge + shell seam) before every dive.",
      "Field swap: reverse screws, replace $19 cartridge, re-torque.",
    ],
    tools: ["CNC mill", "Overmold tooling", "Coin for field swap"],
    notes: "Two sealing boundaries — inspect both. Flagship for fielded product.",
  },
  {
    id: "A4",
    name: "Titan-20",
    family: "A",
    familyTitle: "Force-Sensed Rigid",
    depthM: 20,
    weightG: 205,
    sensing: "Load cell",
    image: "assets/A4-titan-20-blueprint.png",
    cadParts: {"shell_front": {"stl": "shell_front.stl", "step": "shell_front.step", "volume_mm3": 88564.4}, "shell_back": {"stl": "shell_back.stl", "step": "shell_back.step", "volume_mm3": 93107.4}, "window_blank": {"stl": "window_blank.stl", "step": "window_blank.step", "volume_mm3": 21841.6}},
    envelope: "rigid-heavy",
    outer: { L: 172, W: 92, H: 32 },
    aperture: { L: 146, W: 68 },
    window: { material: "Mg-aluminate spinel", t: 2.2, mount: "silicone diaphragm hi-preload" },
    shell: { material: "Ti-6Al-4V bezel + back", t: 2.0 },
    bom: [
      { qty: 1, part: "Ti-6Al-4V bezel CNC", note: "Long machine time" },
      { qty: 1, part: "Ti-6Al-4V back", note: "Double O-ring groove" },
      { qty: 1, part: "Spinel window 2.2 mm", note: "NVIS-compatible optical grade" },
      { qty: 4, part: "Hi-preload load cells", note: "Null hydrostatic baseline" },
      { qty: 2, part: "O-ring set (double seam)", note: "Viton preferred" },
      { qty: 1, part: "PCB + battery + BLE", note: "" },
    ],
    assembly: [
      "Machine Ti bezel/back; polish O-ring lands.",
      "Seat spinel on hi-preload diaphragm; set cell preload for 20 m baseline.",
      "Assemble double O-ring seam; verify compression %. ",
      "Drop test fixture to 1.8 m × 26 faces per 516.8 Proc IV target.",
      "Salt fog 96 h — Ti inert path.",
    ],
    tools: ["Ti CNC + coolant", "Spinel vendor", "Drop tower"],
    notes: "Cost dominated by Ti machining. Spec only when abuse rating is non-negotiable.",
  },
  {
    id: "B5",
    name: "Hall-Glove",
    family: "B",
    familyTitle: "Alternative Sensing",
    depthM: 6,
    weightG: 150,
    sensing: "Magnetic",
    image: "assets/B5-hall-glove-blueprint.png",
    cadParts: {"shell_front": {"stl": "shell_front.stl", "step": "shell_front.step", "volume_mm3": 53873.3}, "shell_back": {"stl": "shell_back.stl", "step": "shell_back.step", "volume_mm3": 57240.2}, "window_blank": {"stl": "window_blank.stl", "step": "window_blank.step", "volume_mm3": 15540.0}},
    envelope: "rigid-standard",
    outer: { L: 168, W: 88, H: 25 },
    aperture: { L: 148, W: 70 },
    window: { material: "Glass fixed", t: 1.5, mount: "rigid bond (no diaphragm)" },
    shell: { material: "CFRP + nylon bezel", t: 1.2 },
    bom: [
      { qty: 1, part: "CFRP shell (A2 envelope)", note: "No load-cell bosses" },
      { qty: 1, part: "Fixed glass window", note: "Passive cover" },
      { qty: 1, part: "8×16 Hall array flex", note: "Laminate behind glass" },
      { qty: 1, part: "Hall sense PCB", note: "" },
      { qty: 1, part: "5 mm neoprene glove", note: "Companion" },
      { qty: 1, part: "N42 NdFeB pellet", note: "Epoxy-seal in fingertip" },
    ],
    assembly: [
      "Laminate Hall array to inner glass; align to UI grid.",
      "Bond glass rigidly into CFRP (no diaphragm).",
      "Epoxy N42 pellet into glove fingertip; seal.",
      "Calibrate gradient → XY map with glove on fixture.",
    ],
    tools: ["Hall array flex fab", "Glove sewing/epoxy"],
    notes: "Bare finger will not work. Ship glove as required accessory.",
  },
  {
    id: "B6",
    name: "Stylus-EMR",
    family: "B",
    familyTitle: "Alternative Sensing",
    depthM: 6,
    weightG: 156,
    sensing: "Resonant",
    image: "assets/B6-stylus-emr-blueprint.png",
    cadParts: {"shell_front": {"stl": "shell_front.stl", "step": "shell_front.step", "volume_mm3": 69941.3}, "shell_back": {"stl": "shell_back.stl", "step": "shell_back.step", "volume_mm3": 77396.3}, "window_blank": {"stl": "window_blank.stl", "step": "window_blank.step", "volume_mm3": 15540.0}},
    envelope: "rigid-standard",
    outer: { L: 168, W: 92, H: 28 },
    aperture: { L: 148, W: 70 },
    window: { material: "Glass fixed", t: 1.5, mount: "rigid" },
    shell: { material: "AZ91D Mg + PEO", t: 1.8 },
    bom: [
      { qty: 1, part: "Mg shell + PEO", note: "Side channel for stylus" },
      { qty: 1, part: "EMR coil grid + ASIC", note: "Wacom-type" },
      { qty: 1, part: "Passive LC stylus", note: "No battery" },
      { qty: 1, part: "Coiled tether + latch", note: "15 N release" },
      { qty: 1, part: "Sealed stow channel", note: "" },
    ],
    assembly: [
      "Mount EMR grid behind fixed glass; tune for seawater dielectric.",
      "Assemble stylus LC tip; pot and waterproof body.",
      "Install coiled tether; verify 15 N release before loss.",
      "Stow channel O-ring seal check.",
    ],
    tools: ["EMR ASIC kit", "Dielectric fixture (salt water)"],
    notes: "Carry spare stylus. Tether failure = total input loss.",
  },
  {
    id: "B7",
    name: "Lamb-Wave",
    family: "B",
    familyTitle: "Alternative Sensing",
    depthM: 6,
    weightG: 148,
    sensing: "Acoustic",
    image: "assets/B7-lamb-wave-blueprint.png",
    cadParts: {"shell_front": {"stl": "shell_front.stl", "step": "shell_front.step", "volume_mm3": 53873.3}, "shell_back": {"stl": "shell_back.stl", "step": "shell_back.step", "volume_mm3": 57240.2}, "window_blank": {"stl": "window_blank.stl", "step": "window_blank.step", "volume_mm3": 15540.0}},
    envelope: "rigid-standard",
    outer: { L: 168, W: 88, H: 25 },
    aperture: { L: 148, W: 70 },
    window: { material: "Bare glass", t: 1.5, mount: "rigid edge bond" },
    shell: { material: "CFRP", t: 1.2 },
    bom: [
      { qty: 1, part: "CFRP shell", note: "" },
      { qty: 1, part: "Glass plate", note: "No coatings in optical path" },
      { qty: 4, part: "Piezo transducers", note: "Edge-bonded" },
      { qty: 1, part: "DSP board", note: "TOA triangulation" },
      { qty: 1, part: "Vibration isolators", note: "Hull noise" },
    ],
    assembly: [
      "Bond piezos to four glass edges; rigid mount glass to shell.",
      "Characterize dry plate modes; store model.",
      "Add wet-dive recalibration routine in firmware.",
      "Isolate shell from vibration sources per 514.8.",
    ],
    tools: ["Piezo bond jig", "Scope / TOA test harness"],
    notes: "Must validate DSP at depth — water damping changes modes.",
  },
  {
    id: "B8",
    name: "Resistive-Hard",
    family: "B",
    familyTitle: "Alternative Sensing",
    depthM: 6,
    weightG: 144,
    sensing: "Resistive",
    image: "assets/B8-resistive-hard-blueprint.png",
    cadParts: {"shell_front": {"stl": "shell_front.stl", "step": "shell_front.step", "volume_mm3": 56335.3}, "shell_back": {"stl": "shell_back.stl", "step": "shell_back.step", "volume_mm3": 65534.1}, "window_blank": {"stl": "window_blank.stl", "step": "window_blank.step", "volume_mm3": 15540.0}},
    envelope: "rigid-standard",
    outer: { L: 168, W: 88, H: 26 },
    aperture: { L: 148, W: 70 },
    window: { material: "Hard-coated PC + resistive film", t: 1.2, mount: "flex laminate" },
    shell: { material: "AZ91D Mg + PEO", t: 1.8 },
    bom: [
      { qty: 1, part: "Mg shell + PEO", note: "" },
      { qty: 1, part: "PC lens hard-coat", note: "Outer" },
      { qty: 1, part: "4-wire resistive film", note: "ITO + microdots" },
      { qty: 1, part: "Resistive sense IC", note: "Low cost" },
      { qty: 1, part: "Battery + BLE", note: "" },
    ],
    assembly: [
      "Laminate resistive film to inner PC; keep flex under touch.",
      "Bond stack into Mg frame.",
      "Calibrate corners; verify glove/nail/stylus.",
      "Plan film as consumable (~1M actuations).",
    ],
    tools: ["Laminator", "4-wire calibrator"],
    notes: "Ship-first candidate: lowest tech risk and unit cost.",
  },
  {
    id: "B9",
    name: "Gap-Cap",
    family: "B",
    familyTitle: "Alternative Sensing",
    depthM: 6,
    weightG: 146,
    sensing: "Cap. gap",
    image: "assets/B9-gap-cap-blueprint.png",
    cadParts: {"shell_front": {"stl": "shell_front.stl", "step": "shell_front.step", "volume_mm3": 56335.3}, "shell_back": {"stl": "shell_back.stl", "step": "shell_back.step", "volume_mm3": 65534.1}, "window_blank": {"stl": "window_blank.stl", "step": "window_blank.step", "volume_mm3": 15540.0}},
    envelope: "rigid-standard",
    outer: { L: 168, W: 88, H: 26 },
    aperture: { L: 148, W: 70 },
    window: { material: "Glass", t: 1.5, mount: "short-throw diaphragm" },
    shell: { material: "AZ91D Mg + PEO", t: 1.8 },
    bom: [
      { qty: 1, part: "Mg shell + PEO", note: "" },
      { qty: 1, part: "Glass + short-throw diaphragm", note: "Micron travel" },
      { qty: 1, part: "Grounded electrode backplate", note: "0.3 mm gap" },
      { qty: 1, part: "Cap-sense IC", note: "µA quiescent" },
      { qty: 1, part: "Small LiPo + BLE", note: "10 g budget" },
    ],
    assembly: [
      "Fixture backplate to set 0.3 mm dry gap under window.",
      "Install short-throw diaphragm; verify micron deflection under finger force.",
      "Enlarge UI hit targets in companion software (~4 mm resolution).",
    ],
    tools: ["Feeler gauge / optical gap check", "Cap-sense eval board"],
    notes: "Best standby life. Coarsest glass-window resolution.",
  },
  {
    id: "C10",
    name: "Crownpad",
    family: "C",
    familyTitle: "Control Surfaces",
    depthM: 10,
    weightG: 112,
    sensing: "Keys only",
    image: "assets/C10-crownpad-blueprint.png",
    cadParts: {"shell_front": {"stl": "shell_front.stl", "step": "shell_front.step", "volume_mm3": 47842.5}, "shell_back": {"stl": "shell_back.stl", "step": "shell_back.step", "volume_mm3": 52417.1}, "window_blank": {"stl": "window_blank.stl", "step": "window_blank.step", "volume_mm3": 9100.0}},
    envelope: "control-compact",
    outer: { L: 165, W: 86, H: 24 },
    aperture: { L: 140, W: 65 },
    window: { material: "PC viewing only", t: 1.0, mount: "fixed gasket" },
    shell: { material: "Injection PPA", t: 1.5 },
    bom: [
      { qty: 1, part: "PPA shell (injection)", note: "Tooling required" },
      { qty: 1, part: "PC viewing window", note: "No load path" },
      { qty: 1, part: "Sealed rotary encoder", note: "Silicone boot" },
      { qty: 1, part: "5-way hat switch", note: "Silicone boot" },
      { qty: 4, part: "Programmable keys", note: "Silicone boots" },
      { qty: "set", part: "NVIS Green A LEDs", note: "MIL-STD-3009" },
    ],
    assembly: [
      "Mold PPA shell; insert window gasket.",
      "Mount encoder, hat, keys under boots; pot PCB.",
      "Wire NVIS backlight; verify 3009 Green A.",
      "Map key events to companion app HID profile.",
    ],
    tools: ["Injection mold", "Switch boot tooling"],
    notes: "Fewest failure modes. App must support discrete remapping.",
  },
  {
    id: "C11",
    name: "Tether-Puck",
    family: "C",
    familyTitle: "Control Surfaces",
    depthM: 20,
    weightG: 140,
    sensing: "Wired puck",
    image: "assets/C11-tether-puck-blueprint.png",
    cadParts: {"shell_front": {"stl": "shell_front.stl", "step": "shell_front.step", "volume_mm3": 34398.9}, "shell_back": {"stl": "shell_back.stl", "step": "shell_back.step", "volume_mm3": 42150.1}, "tether_puck": {"stl": "tether_puck.stl", "step": "tether_puck.step", "volume_mm3": 54725.1}, "window_blank": {"stl": "window_blank.stl", "step": "window_blank.step", "volume_mm3": 8832.0}},
    envelope: "split-puck",
    outer: { L: 160, W: 84, H: 22 },
    aperture: { L: 138, W: 64 },
    window: { material: "PC fixed", t: 1.0, mount: "fixed" },
    shell: { material: "PPA case + PPA puck", t: 1.5 },
    bom: [
      { qty: 1, part: "PPA dry case", note: "98 g target" },
      { qty: 1, part: "Bulkhead connector + gland", note: "Only penetration — marine rated" },
      { qty: 1, part: "Puck body + IP68 thumbstick", note: "42 g" },
      { qty: 1, part: "Coiled marine cable", note: "15 N pull" },
      { qty: 2, part: "Puck buttons", note: "" },
      { qty: 1, part: "Chest/wrist stow clip", note: "" },
    ],
    assembly: [
      "Install bulkhead with compression gland; torque to marine spec.",
      "Wire thumbstick + buttons through cable; strain-relieve.",
      "Pressure test connector at 20 m equivalent.",
      "Coil cable; fit stow clip.",
    ],
    tools: ["Marine bulkhead kit", "Cable potting"],
    notes: "Bulkhead seal quality gates entire reliability.",
  },
  {
    id: "C12",
    name: "Tilt-Cursor",
    family: "C",
    familyTitle: "Control Surfaces",
    depthM: 6,
    weightG: 96,
    sensing: "IMU",
    image: "assets/C12-tilt-cursor-blueprint.png",
    cadParts: {"shell_front": {"stl": "shell_front.stl", "step": "shell_front.step", "volume_mm3": 31400.4}, "shell_back": {"stl": "shell_back.stl", "step": "shell_back.step", "volume_mm3": 33489.7}, "window_blank": {"stl": "window_blank.stl", "step": "window_blank.step", "volume_mm3": 8432.0}},
    envelope: "control-thin",
    outer: { L: 162, W: 84, H: 18 },
    aperture: { L: 136, W: 62 },
    window: { material: "Thin PC", t: 0.8, mount: "fixed" },
    shell: { material: "Thin-wall PPA", t: 1.0 },
    bom: [
      { qty: 1, part: "Thin PPA shell", note: "Lightest shell" },
      { qty: 1, part: "Thin PC window", note: "Viewing only" },
      { qty: 1, part: "6-axis IMU", note: "~$2" },
      { qty: 1, part: "Index trigger switch", note: "Sealed boot" },
      { qty: 1, part: "Battery + BLE", note: "14 g" },
    ],
    assembly: [
      "Mount IMU aligned to wrist axes; seal trigger.",
      "Firmware: pitch/roll → cursor; re-center gesture.",
      "User-test fatigue >2 min continuous tilt.",
    ],
    tools: ["IMU breakout", "Thin-wall mold"],
    notes: "Absolute lightest. Precision and fatigue are the trade.",
  },
  {
    id: "C13",
    name: "Voice-PTT",
    family: "C",
    familyTitle: "Control Surfaces",
    depthM: 20,
    weightG: 104,
    sensing: "Voice",
    image: "assets/C13-voice-ptt-blueprint.png",
    cadParts: {"shell_front": {"stl": "shell_front.stl", "step": "shell_front.step", "volume_mm3": 41581.6}, "shell_back": {"stl": "shell_back.stl", "step": "shell_back.step", "volume_mm3": 47000.8}, "window_blank": {"stl": "window_blank.stl", "step": "window_blank.step", "volume_mm3": 8832.0}},
    envelope: "control-compact",
    outer: { L: 164, W: 85, H: 22 },
    aperture: { L: 138, W: 64 },
    window: { material: "PC fixed", t: 1.0, mount: "fixed" },
    shell: { material: "PPA", t: 1.5 },
    bom: [
      { qty: 1, part: "PPA shell", note: "" },
      { qty: 1, part: "PC window", note: "Display only" },
      { qty: 1, part: "PTT sealed switch", note: "" },
      { qty: 1, part: "Audio codec PCB", note: "" },
      { qty: 1, part: "Bone-conduction transducer", note: "Worn separately" },
      { qty: 1, part: "Mask-strap clip", note: "Mastoid pressure" },
    ],
    assembly: [
      "Build display-only case with PTT.",
      "Wire bone transducer to clip; set mastoid pressure pad.",
      "Voice command vocabulary only — no free dictation.",
    ],
    tools: ["Bone-conduction module", "Clip mold"],
    notes: "Avoid tactical/wildlife noise-discipline missions.",
  },
  {
    id: "D14",
    name: "Rolltop",
    family: "D",
    familyTitle: "Non-Rigid & Mission",
    depthM: 6,
    weightG: 122,
    sensing: "Load cell",
    image: "assets/D14-rolltop-blueprint.png",
    cadParts: {"rigid_bezel": {"stl": "rigid_bezel.stl", "step": "rigid_bezel.step", "volume_mm3": 82096.0}, "window_blank": {"stl": "window_blank.stl", "step": "window_blank.step", "volume_mm3": 15540.0}, "fabric_cut_pattern": {"stl": "fabric_cut_pattern.stl", "step": "fabric_cut_pattern.step", "volume_mm3": 14080.0}},
    envelope: "soft-rolltop",
    outer: { L: 175, W: 95, H: 40 },
    aperture: { L: 148, W: 70 },
    window: { material: "Glass in rigid bezel", t: 1.5, mount: "A1 load-cell bezel" },
    shell: { material: "500D aramid + TPU coat", t: "fabric" },
    bom: [
      { qty: 1, part: "Aramid/TPU body", note: "RF welded seams" },
      { qty: 1, part: "Rigid bezel + window + 4 cells", note: "61 g" },
      { qty: 2, part: "Side-release buckles", note: "Roll clamp" },
      { qty: 1, part: "Roll bar / clamp strip", note: "3 folds" },
      { qty: 1, part: "Battery + BLE", note: "" },
    ],
    assembly: [
      "RF-weld fabric body to rigid bezel seal lip.",
      "Install A1-style sensing bezel.",
      "Train fold: 3 rolls + buckle clamp; dunk test.",
      "Verify packed volume ~40% of rigid case.",
    ],
    tools: ["RF welder", "Fabric pattern", "Dunk tank"],
    notes: "Hard bezel edge is impact weak point — pad in bag.",
  },
  {
    id: "D15",
    name: "Oilfill-100",
    family: "D",
    familyTitle: "Non-Rigid & Mission",
    depthM: 100,
    weightG: 178,
    sensing: "Keys",
    image: "assets/D15-oilfill-100-blueprint.png",
    cadParts: {"oil_shell": {"stl": "oil_shell.stl", "step": "oil_shell.step", "volume_mm3": 45675.6}, "oil_lid": {"stl": "oil_lid.stl", "step": "oil_lid.step", "volume_mm3": 15300.0}},
    envelope: "oilfill",
    outer: { L: 170, W: 90, H: 35 },
    aperture: { L: 50, W: 30 },
    window: { material: "Sealed OLED panel (not phone)", t: 2.0, mount: "independent seal" },
    shell: { material: "1 mm PPA + rolling diaphragm", t: 1.0 },
    bom: [
      { qty: 1, part: "Thin PPA shell", note: "1 mm walls" },
      { qty: 1, part: "Rolling silicone diaphragm", note: "" },
      { qty: 1, part: "Silicone oil fill", note: "Phone-safe, optically clear" },
      { qty: 1, part: "Oil reservoir + bleed valve", note: "Thermal expansion volume" },
      { qty: 1, part: "Sealed OLED + MCU", note: "BLE relay from phone" },
      { qty: 1, part: "Encoder + hat keys", note: "C10-style" },
    ],
    assembly: [
      "Install phone in oil chamber; fill silicone oil; bleed bubbles.",
      "Size reservoir for −32…+71 °C expansion.",
      "Seal separate OLED readout; pair MCU↔phone BLE.",
      "Chamber test to 100 m equivalent (10 bar).",
      "Schedule periodic oil top-off maintenance.",
    ],
    tools: ["Pressure chamber 10 bar", "Oil fill/bleed station"],
    notes: "Only real-depth design. Phone screen sacrificed for oil immersion.",
  },
  {
    id: "D16",
    name: "Floatline",
    family: "D",
    familyTitle: "Non-Rigid & Mission",
    depthM: 6,
    weightG: 168,
    sensing: "Load cell",
    image: "assets/D16-floatline-blueprint.png",
    cadParts: {"shell_front": {"stl": "shell_front.stl", "step": "shell_front.step", "volume_mm3": 56335.3}, "shell_back": {"stl": "shell_back.stl", "step": "shell_back.step", "volume_mm3": 65534.1}, "foam_collar": {"stl": "foam_collar.stl", "step": "foam_collar.step", "volume_mm3": 511712.4}, "window_blank": {"stl": "window_blank.stl", "step": "window_blank.step", "volume_mm3": 15540.0}},
    envelope: "rigid-foam",
    outer: { L: 190, W: 110, H: 45 },
    aperture: { L: 148, W: 70 },
    window: { material: "A1 core window", t: 1.5, mount: "A1" },
    shell: { material: "A1 Mg core + syntactic foam", t: "collar" },
    bom: [
      { qty: 1, part: "A1 Lightline core", note: "Unmodified 153 g" },
      { qty: 1, part: "Syntactic foam collar", note: "~0.55 g/cc, 15 g → +40 N" },
    ],
    assembly: [
      "Mold syntactic foam collar around finished A1.",
      "Verify buoyancy: ~40 N positive in fresh water.",
      "Confirm foam crush depth ≥ A1 rating.",
    ],
    tools: ["Foam mold", "Buoyancy tank"],
    notes: "Insurance feature — bulk vs pocketability trade.",
  },
  {
    id: "D17",
    name: "Chestboard",
    family: "D",
    familyTitle: "Non-Rigid & Mission",
    depthM: 10,
    weightG: 184,
    sensing: "Keys",
    image: "assets/D17-chestboard-blueprint.png",
    cadParts: {"shell_front": {"stl": "shell_front.stl", "step": "shell_front.step", "volume_mm3": 194353.9}, "shell_back": {"stl": "shell_back.stl", "step": "shell_back.step", "volume_mm3": 237714.3}, "window_blank": {"stl": "window_blank.stl", "step": "window_blank.step", "volume_mm3": 15810.0}},
    envelope: "landscape-molle",
    outer: { L: 200, W: 120, H: 28 },
    aperture: { L: 155, W: 85 },
    window: { material: "PC landscape", t: 1.2, mount: "fixed" },
    shell: { material: "PPA + MOLLE plate", t: 1.8 },
    bom: [
      { qty: 1, part: "Landscape PPA shell", note: "" },
      { qty: 1, part: "Enlarged PC window", note: "" },
      { qty: 6, part: "12 mm sealed dome keys", note: "Silicone boots" },
      { qty: 1, part: "MOLLE mounting plate", note: "28 g" },
      { qty: "set", part: "NVIS key LEDs", note: "" },
    ],
    assembly: [
      "Orient phone landscape; enlarge window accordingly.",
      "Mount six dome keys; map to app functions.",
      "Attach MOLLE plate; vibration-test on harness (514.8).",
    ],
    tools: ["MOLLE plate fab", "Harness vibration rig"],
    notes: "Requires plate carrier / harness — not handheld.",
  },
  {
    id: "D18",
    name: "Gauntlet",
    family: "D",
    familyTitle: "Non-Rigid & Mission",
    depthM: 20,
    weightG: 108,
    sensing: "Crown",
    image: "assets/D18-gauntlet-blueprint.png",
    cadParts: {"shell_front": {"stl": "shell_front.stl", "step": "shell_front.step", "volume_mm3": 8779.8}, "shell_back": {"stl": "shell_back.stl", "step": "shell_back.step", "volume_mm3": 11617.5}, "window_blank": {"stl": "window_blank.stl", "step": "window_blank.step", "volume_mm3": 1444.0}},
    envelope: "forearm",
    outer: { L: 95, W: 70, H: 28 },
    aperture: { L: 38, W: 38 },
    window: { material: "PC 38×38", t: 1.0, mount: "fixed" },
    shell: { material: "PPA + strap mount", t: 1.5 },
    bom: [
      { qty: 1, part: "PPA shell + strap lugs", note: "" },
      { qty: 1, part: "38×38 PC window", note: "Cropped UI" },
      { qty: 1, part: "Side rotary crown", note: "" },
      { qty: 2, part: "Sealed keys", note: "" },
      { qty: 1, part: "Liquid-filled compass repeater", note: "Mechanical, zero power" },
      { qty: 1, part: "Forearm strap", note: "514.8 fatigue tested" },
    ],
    assembly: [
      "Mount small window; implement crown-driven crop region.",
      "Install mechanical compass repeater in bezel; degauss check.",
      "Strap-mount fatigue test for wrist motion.",
    ],
    tools: ["Compass repeater vendor", "Strap hardware"],
    notes: "Glanceable data only. Heading survives dead phone.",
  },
];

window.NEREID_ENVELOPES = {
  "rigid-standard": "Standard rigid sealed pocket over phone screen",
  "rigid-heavy": "Thick-wall abuse envelope",
  "control-compact": "Viewing port + physical controls",
  "control-thin": "Minimum-mass control shell",
  "split-puck": "Dry case + wired puck",
  "soft-rolltop": "Fabric body + rigid sensing bezel",
  "oilfill": "Pressure-compensated oil volume",
  "rigid-foam": "Rigid core + buoyancy collar",
  "landscape-molle": "Landscape torso mount",
  forearm: "Wrist/forearm mount, cropped aperture",
};
